// supabase/functions/update-news/gemini.ts: Service for formatting articles with Gemini.
// @ts-nocheck - This is a Deno file and should not be type-checked by the frontend's TypeScript compiler.
import { GoogleGenAI, Type } from 'https://esm.sh/@google/genai@^1.16.0';
import { supabaseAdmin, incrementKeyCalls, incrementKeyFailures } from './supabase.ts';

let currentKeyIndex = 0;

const rotateApiKey = async (logger, geminiApiKeys) => {
  if (geminiApiKeys.length === 0) return null;
    const failedKeyObj = geminiApiKeys[currentKeyIndex];
      
        logger.warn(`Gemini key ...${failedKeyObj.api_key.slice(-4)} failed. Rotating...`);
          
            // Mark failure in DB (exhausts after 3 failures)
              await incrementKeyFailures(failedKeyObj.id, 3);

                currentKeyIndex = (currentKeyIndex + 1) % geminiApiKeys.length;
                  
                    if (currentKeyIndex === 0) {
                        logger.error('All Gemini API keys have failed within this cycle. Aborting subsequent attempts.');
                            return null;
                              }
                                
                                  const newKeyObj = geminiApiKeys[currentKeyIndex];
                                    logger.info(`Switched to Gemini key ...${newKeyObj.api_key.slice(-4)}.`);
                                      
                                        return new GoogleGenAI({ apiKey: newKeyObj.api_key });
                                        };

                                        const BATCH_SYSTEM_PROMPT = `You are an expert news writer and article formatter. You will receive a JSON array of raw news articles. For EACH article, you MUST perform two tasks:
                                        1.  **Generate a Display Title:** Create a concise, catchy, and SEO-friendly title that is 7-8 words long. This should capture the essence of the article.
                                        2.  **Format the Article Body:** Rewrite the article's content into a detailed, long-form news article formatted with rich markdown, following the structure below precisely.

                                        **Formatting Structure for EACH Article Body:**
                                        1.  **Lead Paragraph:** Start with a single, strong introductory paragraph that hooks the reader and summarizes the most critical information (the who, what, where, when, and why).
                                        2.  **Detailed Body:** Continue with a well-structured, multi-paragraph body that elaborates on the story. You MUST use subheadings (e.g., #### Background, #### The Details, #### What's Next) where appropriate to organize the content and improve readability. The goal is to create a comprehensive and engaging article, not just a brief summary.

                                        **Output Requirement:**
                                        You MUST respond with a single, valid JSON array. Each object in the array must contain three keys:
                                        - \`original_url\`: The URL of the article you just formatted.
                                        - \`display_title\`: The new 7-8 word title you generated.
                                        - \`formatted_markdown\`: The full markdown content you generated for that article. The markdown string MUST use newline characters (\\n) to separate paragraphs and headings for correct rendering.

                                        Handle each article independently. If an article's content is missing or invalid, skip it and do not include it in your final JSON array output.`;

                                        export const formatArticleBatchWithGemini = async (articles, logger, geminiApiKeys) => {
                                          if (articles.length === 0) return new Map();
                                            
                                              let currentKeyObj = geminiApiKeys[currentKeyIndex];
                                                let geminiAi = new GoogleGenAI({ apiKey: currentKeyObj.api_key });
                                                  
                                                    const articlesForPrompt = articles.map((a) => ({
                                                          title: a.title,
                                                                source: a.source.name,
                                                                      url: a.url,
                                                                            content: a.content || a.description || ''
                                                                              }));
                                                                                const prompt = JSON.stringify(articlesForPrompt);
                                                                                  
                                                                                    try {
                                                                                        const response = await geminiAi.models.generateContent({
                                                                                              model: 'gemini-2.5-flash-lite',
                                                                                                    contents: prompt,
                                                                                                          config: {
                                                                                                                  systemInstruction: BATCH_SYSTEM_PROMPT,
                                                                                                                          responseMimeType: 'application/json',
                                                                                                                                  responseSchema: {
                                                                                                                                            type: Type.ARRAY,
                                                                                                                                                      items: {
                                                                                                                                                                  type: Type.OBJECT,
                                                                                                                                                                              properties: {
                                                                                                                                                                                            original_url: { type: Type.STRING },
                                                                                                                                                                                                          display_title: { type: Type.STRING },
                                                                                                                                                                                                                        formatted_markdown: { type: Type.STRING }
                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                required: ["original_url", "display_title", "formatted_markdown"]
                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                    const jsonText = response.text.trim();
                                                                                                                                                                                                                                                                                        if (!jsonText) {
                                                                                                                                                                                                                                                                                              logger.warn('Gemini returned an empty response for the batch. No articles will be formatted.');
                                                                                                                                                                                                                                                                                                    return new Map();
                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                const results = JSON.parse(jsonText);
                                                                                                                                                                                                                                                                                                                    const resultMap = new Map();
                                                                                                                                                                                                                                                                                                                        for (const res of results){
                                                                                                                                                                                                                                                                                                                              if (res.original_url && res.formatted_markdown && res.display_title) {
                                                                                                                                                                                                                                                                                                                                      resultMap.set(res.original_url, {
                                                                                                                                                                                                                                                                                                                                                title: res.display_title,
                                                                                                                                                                                                                                                                                                                                                          markdown: res.formatted_markdown
                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                    logger.success(`Batch formatted ${resultMap.size} articles.`);
                                                                                                                                                                                                                                                                                                                                                                                        // Success! Increment calls
                                                                                                                                                                                                                                                                                                                                                                                            await incrementKeyCalls(currentKeyObj.id);
                                                                                                                                                                                                                                                                                                                                                                                                return resultMap;
                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                      } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                          logger.error(`Gemini batch formatting failed: ${error.message}`);
                                                                                                                                                                                                                                                                                                                                                                                                              const isRateLimit = error.message.includes('429');
                                                                                                                                                                                                                                                                                                                                                                                                                  const isAuthError = error.message.includes('API key not valid');
                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                          if (isRateLimit || isAuthError) {
                                                                                                                                                                                                                                                                                                                                                                                                                                const newClient = await rotateApiKey(logger, geminiApiKeys);
                                                                                                                                                                                                                                                                                                                                                                                                                                      if (newClient) {
                                                                                                                                                                                                                                                                                                                                                                                                                                              logger.info('Retrying Gemini call with new key...');
                                                                                                                                                                                                                                                                                                                                                                                                                                                      try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                const retryResponse = await newClient.models.generateContent({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            model: 'gemini-2.5-flash',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        contents: prompt,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    config: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  systemInstruction: BATCH_SYSTEM_PROMPT,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                responseMimeType: 'application/json',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              responseSchema: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              type: Type.ARRAY,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              items: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                type: Type.OBJECT,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  properties: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      original_url: { type: Type.STRING },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          display_title: { type: Type.STRING },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              formatted_markdown: { type: Type.STRING }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  required: ["original_url", "display_title", "formatted_markdown"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const jsonText = retryResponse.text.trim();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const results = JSON.parse(jsonText);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const resultMap = new Map();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for (const res of results){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (res.original_url && res.formatted_markdown && res.display_title) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  resultMap.set(res.original_url, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  title: res.display_title,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  markdown: res.formatted_markdown
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                logger.success(`Batch formatted ${resultMap.size} articles on retry.`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Success on retry! Increment calls for the NEW key
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              await incrementKeyCalls(geminiApiKeys[currentKeyIndex].id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return resultMap;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (retryError) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          logger.error(`Gemini retry failed: ${retryError.message}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                logger.warn('Could not format articles in this batch due to a persistent Gemini error.');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return new Map();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      };
