// supabase/functions/update-news/news.ts: Service for fetching news from GNews.
// @ts-nocheck - This is a Deno file and should not be type-checked by the frontend's TypeScript compiler.
import { formatArticleBatchWithGemini } from './gemini.ts';
import { supabaseAdmin, incrementKeyCalls, incrementKeyFailures } from './supabase.ts';
import { delay } from './utils.ts';

let currentGNewsKeyIndex = 0;
const NEWS_API_URL = 'https://gnews.io/api/v4/top-headlines';

const rotateGNewsApiKey = async (logger, gnewsApiKeys) => {
  if (gnewsApiKeys.length === 0) return false;
    const failedKeyObj = gnewsApiKeys[currentGNewsKeyIndex];
      
        logger.warn(`GNews key ...${failedKeyObj.api_key.slice(-4)} failed or was rate-limited. Rotating...`);
          
            // Mark failure in DB (exhausts after 3 failures)
              await incrementKeyFailures(failedKeyObj.id, 3);

                currentGNewsKeyIndex = (currentGNewsKeyIndex + 1) % gnewsApiKeys.length;
                  if (currentGNewsKeyIndex === 0) {
                      logger.error('All GNews API keys have been tried and failed. Aborting category fetch.');
                          return false;
                            }
                              const newKeyObj = gnewsApiKeys[currentGNewsKeyIndex];
                                logger.info(`Switched to GNews key ...${newKeyObj.api_key.slice(-4)}.`);
                                  return true;
                                  };

const fetchWithRetryAndRotation = async (url, logger, gnewsApiKeys, retries = 2) => {
    const originalUrl = new URL(url);
    const currentKeyObj = gnewsApiKeys[currentGNewsKeyIndex];
    try {
        // Sanitize the API key just in case it has trailing spaces or quotes
        const cleanApiKey = currentKeyObj.api_key.replace(/["'\s]/g, '');
        originalUrl.searchParams.set('apikey', cleanApiKey);
        
        const response = await fetch(originalUrl.toString());
            
        if (!response.ok) {
            const errText = await response.text();
            logger.error(`GNews API Error detail: ${errText}`);
            
            // Rotate on 429 (Rate Limit), 401 (Invalid Key), 403 (Quota Exceeded), or 400 (Bad Request from dirty key)
            const shouldRotate = [429, 401, 403, 400].includes(response.status);
            
            if (shouldRotate && retries > 0) {
                const rotated = await rotateGNewsApiKey(logger, gnewsApiKeys);
                if (!rotated) throw new Error('All GNews API keys failed.');
                await delay(1000);
                return fetchWithRetryAndRotation(url, logger, gnewsApiKeys, retries - 1);
            }
            throw new Error(`GNews API Error: ${response.status} ${response.statusText} Details: ${errText}`);
        }
            
        // Success! Increment calls
        await incrementKeyCalls(currentKeyObj.id);
        return response;
                                                                                                                                            } catch (error) {
                                                                                                                                                if (retries > 0) {
                                                                                                                                                      logger.warn(`GNews API fetch error: ${error.message}. Retrying... (${retries} attempts left)`);
                                                                                                                                                            await delay(2000);
                                                                                                                                                                  return fetchWithRetryAndRotation(url, logger, gnewsApiKeys, retries - 1);
                                                                                                                                                                      }
                                                                                                                                                                          throw error;
                                                                                                                                                                            }
                                                                                                                                                                            };

                                                                                                                                                                            export const processNewsCategory = async (category, logger, gnewsApiKeys, geminiApiKeys) => {
                                                                                                                                                                              let articlesUpdated = 0;
                                                                                                                                                                                try {
                                                                                                                                                                                    const response = await fetchWithRetryAndRotation(`${NEWS_API_URL}?category=${category}&lang=en&max=10`, logger, gnewsApiKeys);
                                                                                                                                                                                        const newsData = await response.json();
                                                                                                                                                                                            
                                                                                                                                                                                                if (newsData.totalArticles === 0) {
                                                                                                                                                                                                      logger.info(`[${category}] GNews API returned 0 articles.`);
                                                                                                                                                                                                            logger.addSummary(`[${category}] Fetched: 0, Formatted: 0, Failed: 0`);
                                                                                                                                                                                                                  return { success: true, articlesUpdated: 0 };
                                                                                                                                                                                                                      }
                                                                                                                                                                                                                          
                                                                                                                                                                                                                              const articles = newsData.articles;
                                                                                                                                                                                                                                  if (!articles || articles.length === 0) {
                                                                                                                                                                                                                                        logger.warn(`[${category}] No articles array found.`);
                                                                                                                                                                                                                                              logger.addSummary(`[${category}] Fetched: 0, Formatted: 0, Failed: 0`);
                                                                                                                                                                                                                                                    return { success: true, articlesUpdated: 0 };
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                logger.success(`[${category}] Fetched ${articles.length} raw articles.`);
                                                                                                                                                                                                                                                                    const formattedArticlesMap = await formatArticleBatchWithGemini(articles, logger, geminiApiKeys);
                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                            const successfulArticles = articles.map((article) => {
                                                                                                                                                                                                                                                                                  const formattedData = formattedArticlesMap.get(article.url);
                                                                                                                                                                                                                                                                                        if (formattedData) {
                                                                                                                                                                                                                                                                                                const updatedArticleData = { ...article };
                                                                                                                                                                                                                                                                                                        updatedArticleData.title = formattedData.title;
                                                                                                                                                                                                                                                                                                                return {
                                                                                                                                                                                                                                                                                                                          category,
                                                                                                                                                                                                                                                                                                                                    article_data: updatedArticleData,
                                                                                                                                                                                                                                                                                                                                              formatted_content_md: { markdown: formattedData.markdown }
                                                                                                                                                                                                                                                                                                                                                      };
                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                  return null;
                                                                                                                                                                                                                                                                                                                                                                      }).filter(Boolean);
                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                              const successCount = successfulArticles.length;
                                                                                                                                                                                                                                                                                                                                                                                  const failedCount = articles.length - successCount;
                                                                                                                                                                                                                                                                                                                                                                                      logger.info(`[${category}] Formatting complete. Success: ${successCount}, Failed: ${failedCount}`);
                                                                                                                                                                                                                                                                                                                                                                                          logger.addSummary(`[${category}] Fetched: ${articles.length}, Formatted: ${successCount}, Failed: ${failedCount}`);
                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                  if (successfulArticles.length === 0) {
                                                                                                                                                                                                                                                                                                                                                                                                        logger.warn(`[${category}] No articles formatted. Skipping DB update.`);
                                                                                                                                                                                                                                                                                                                                                                                                              return { success: true, articlesUpdated: 0 };
                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                          logger.info(`[${category}] Deleting old articles...`);
                                                                                                                                                                                                                                                                                                                                                                                                                              const { error: deleteError } = await supabaseAdmin.from('public_news_articles').delete().eq('category', category);
                                                                                                                                                                                                                                                                                                                                                                                                                                  if (deleteError) throw new Error(`DB delete failed: ${deleteError.message}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                          logger.info(`[${category}] Inserting ${successfulArticles.length} new articles...`);
                                                                                                                                                                                                                                                                                                                                                                                                                                              const { error: insertError } = await supabaseAdmin.from('public_news_articles').insert(successfulArticles);
                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (insertError) throw new Error(`DB insert failed: ${insertError.message}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                          articlesUpdated = successfulArticles.length;
                                                                                                                                                                                                                                                                                                                                                                                                                                                              logger.success(`[${category}] Stored ${articlesUpdated} articles.`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return { success: true, articlesUpdated };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        let simpleError = error.message.includes('GNews') ? "GNews request failed" : error.message;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            logger.error(`[${category}] Process failed: ${simpleError}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return { success: false, articlesUpdated: 0 };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };
